---
#-------------------------------
# General Site Settings

title: Shota Shiiku
author: shiiku419
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Shota Shiiku](https://github.com/shiiku419)

menu:
  - { name: About, link: "/about" }
  - { name: Publications, link: "/blog" }
#  - { name: Portfolio, link: "/portfolio" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Shota Shiiku <br> 
  hero-subtitle: Graduate Student at Shizuoka University 
social:
  #- { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "https://www.instagram.com/shiiku_4193/" }
  #- { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-github", link: "https://github.com/shiiku419" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/%E7%BF%94%E5%A4%AA-%E6%A4%8E%E4%B9%85-95b126283/?originalSubdomain=jp" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: I was born in 2000 and am currently pursuing my graduate studies in the Graduate School at Shizuoka University. I am a member of the Takeuchi Lab., where my primary research focuses on simulating group decision-making processes using reinforcement learning. In addition to my academic pursuits, I enjoy following the NBA and playing basketball.


blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { tag: github/github-original-wordmark.svg }
  - { tag: docker/docker-plain-wordmark.svg }
  - { tag: gitlab/gitlab-original-wordmark.svg }
  - { tag: html5/html5-original-wordmark.svg }
  - { tag: css3/css3-original-wordmark.svg }
  - { tag: javascript/javascript-original.svg }
  - { tag: linux/linux-original.svg }
  - { tag: ruby/ruby-original-wordmark.svg }
  - { tag: tensorflow/tensorflow-original.svg }
  - { tag: python/python-original-wordmark.svg }
  - { tag: react/react-original-wordmark.svg }
  - { tag: pytorch/pytorch-original.svg }


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Intern/Enginner,
      icon: "icon-1.png",
      date: "Jul 2021 - now ",
      organization: "Metadata Inc.",
    }
  - {
      name: Intern/Enginner,
      icon: "icon-2.png",
      date: "Jul 2023",
      organization: "Sansan",
    }

  #- {
   # name: Intern/Enginner,
    #icon: "icon-3.png",
    #date: "Oct 2023",
    #organization: "CyberAgent",
  #}

#-------------------------------
# Certifications Section

certifications-title: Certifications
certifications:
  - {
      name: Tensorflow Developer Certificate,
      icon: "certificate-1.pdf",
      date: "2022",
    }


#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Master of Informatics,
      icon: tf,
      date: "*expected in 2025",
      organization: "Shizuoka University",
    }
  - {
      name: Bachelor of Informatics,
      date: "2023",
      organization: "Shizuoka University",
    }
  - {
      name: High School Certificate,
      date: "2019",
      organization: "Yokkaichi Senior High School",
    }

