// AUTO-GENERATED by scripts/convert-bib.mjs from scripts/bib-source/*.bib.
// Do not hand-edit entries here except for small corrections; re-run the
// script after updating the source .bib files to regenerate from scratch.

export type PublicationCategory =
  | "journal"
  | "paper"
  | "talk"
  | "workshop"
  | "preprint"
  | "domestic"
  | "thesis"
  | "grant";

export type Topic =
  | "decision-making"
  | "collective-behavior"
  | "music-cognition"
  | "sports-analytics"
  | "llm";

export interface PublicationLinks {
  pdf?: string;
  doi?: string;
  url?: string;
}

export interface Publication {
  id: string;
  title: string;
  authors: string[];
  venue: string;
  year: number;
  category: PublicationCategory;
  topics: Topic[];
  links: PublicationLinks;
  preview?: string;
  selected?: boolean;
}

export const publications: Publication[] = [
  {
    id: "shiiku2026jsai-18",
    title: "人とAIの共創社会における集団的創造性",
    authors: [
      "椎久翔太",
      "Raja Marjieh",
      "Manuel Anglada-Tort",
      "Nori Jacoby"
    ],
    venue: "第40回人工知能学会全国大会",
    year: 2026,
    category: "domestic",
    topics: [
      "collective-behavior",
      "llm"
    ],
    links: {}
  },
  {
    id: "shiiku2026hcii-23",
    title: "Trends and Visualization of Team Performance During Clutch Time in Japan's Professional B.League",
    authors: [
      "Shota Shiiku",
      "Jun Ichikawa"
    ],
    venue: "HCI International 2026 Posters, Communications in Computer and Information Science",
    year: 2026,
    category: "paper",
    topics: [
      "sports-analytics"
    ],
    links: {
      doi: "https://doi.org/10.1007/978-3-032-30826-9_63"
    },
    selected: true
  },
  {
    id: "shiiku2026hybrid-26",
    title: "Hybrid Human-AI Societies Balance Creativity and Diversity",
    authors: [
      "Shota Shiiku",
      "Raja Marjieh",
      "Thomas L. Griffiths",
      "Manuel Anglada-Tort",
      "Nori Jacoby"
    ],
    venue: "Under evaluation",
    year: 2026,
    category: "preprint",
    topics: [
      "collective-behavior",
      "llm"
    ],
    links: {}
  },
  {
    id: "shiiku2026mb-27",
    title: "Collective Creativity in Human–AI Hybrid Societies",
    authors: [
      "Shota Shiiku",
      "Raja Marjieh",
      "Manuel Anglada-Tort",
      "Nori Jacoby"
    ],
    venue: "Machine+Behavior Conference 2026 ",
    year: 2026,
    category: "talk",
    topics: [
      "collective-behavior",
      "llm"
    ],
    links: {
      url: "https://machinebehavior.science/program-1"
    }
  },
  {
    id: "usami2025-4",
    title: "野球の試合展開を踏まえたハーフイニング予測モデルの構築",
    authors: [
      "宇佐美翔大",
      "中野暁登",
      "岩田侑己",
      "大西隆之介",
      "椎久翔太",
      "市川淳"
    ],
    venue: "人工知能学会全国大会論文集 第39回 (2025)",
    year: 2025,
    category: "domestic",
    topics: [
      "sports-analytics"
    ],
    links: {}
  },
  {
    id: "hai2025-5",
    title: "ソーシャルネットワークにおける人間とAIの協働がもたらす集団的創造性",
    authors: [
      "Shota Shiiku",
      "Raja Marjieh",
      "Manuel Anglada-Tort",
      "Nori Jacoby"
    ],
    venue: "HAIシンポジウム2025",
    year: 2025,
    category: "domestic",
    topics: [
      "collective-behavior",
      "llm"
    ],
    links: {}
  },
  {
    id: "hcg2024-6",
    title: "Bリーグにおけるクラッチタイムのトレンドおよびパフォーマンスの可視化",
    authors: [
      "椎久翔太",
      "市川淳"
    ],
    venue: "2024年度スポーツデータサイエンスコンペティション",
    year: 2025,
    category: "domestic",
    topics: [
      "sports-analytics"
    ],
    links: {}
  },
  {
    id: "hcg2024-7",
    title: "試合展開の定量化によるハーフイニング予測の検討",
    authors: [
      "宇佐美翔大",
      "中野暁登",
      "岩田侑己",
      "大西隆之介",
      "椎久翔太",
      "市川淳"
    ],
    venue: "2024年度スポーツデータサイエンスコンペティション",
    year: 2025,
    category: "domestic",
    topics: [
      "sports-analytics"
    ],
    links: {}
  },
  {
    id: "shiiku2025dynamics-19",
    title: "Trends and Performance Visualization of Clutch Time in Japan's Professional B.League",
    authors: [
      "Shota Shiiku",
      "Jun Ichikawa"
    ],
    venue: "15th International Symposium on Computer Science in Sport",
    year: 2025,
    category: "paper",
    topics: [
      "sports-analytics"
    ],
    links: {}
  },
  {
    id: "shiiku2025dynamics-20",
    title: "The Dynamics of Collective Creativity in Human-AI Hybrid Societies",
    authors: [
      "Shota Shiiku",
      "Roni Marjieh",
      "Manuel Anglada-Tort",
      "Nori Jacoby"
    ],
    venue: "Proceedings of the Annual Meeting of the Cognitive Science Society",
    year: 2025,
    category: "paper",
    topics: [
      "collective-behavior",
      "llm"
    ],
    links: {},
    selected: true
  },
  {
    id: "shiiku2025jsftii-24",
    title: "Leveraging Emergent Opinion Dynamics in Small-Group Decision-Making: A Simulation-Based Examination of Creativity and Satisfaction",
    authors: [
      "Shota Shiiku",
      "Yugo Takeuchi"
    ],
    venue: "Journal of Japan Society for Fuzzy Theory and Intelligent Informatics",
    year: 2025,
    category: "journal",
    topics: [
      "collective-behavior",
      "decision-making"
    ],
    links: {}
  },
  {
    id: "shiiku2025dynamicscollectivecreativityhumanai-25",
    title: "The Dynamics of Collective Creativity in Human-AI Social Networks",
    authors: [
      "Shota Shiiku",
      "Raja Marjieh",
      "Manuel Anglada-Tort",
      "Nori Jacoby"
    ],
    venue: "",
    year: 2025,
    category: "preprint",
    topics: [
      "collective-behavior",
      "llm"
    ],
    links: {
      url: "https://arxiv.org/abs/2502.17962"
    }
  },
  {
    id: "shii2022phd-1",
    title: "大規模言語モデルによる小集団の創造的意思決定のシミュレーションと満足度の評価",
    authors: [
      "椎久翔太"
    ],
    venue: "修士, 指導教員: 竹内勇剛",
    year: 2024,
    category: "thesis",
    topics: [
      "llm",
      "decision-making"
    ],
    links: {}
  },
  {
    id: "hcg2024-8",
    title: "大規模言語モデルによる小集団の創発的意思決定過程の適応可能性の探究",
    authors: [
      "椎久翔太",
      "竹内勇剛"
    ],
    venue: "電子情報通信学会HCGシンポジウム2024",
    year: 2024,
    category: "domestic",
    topics: [
      "llm",
      "decision-making"
    ],
    links: {}
  },
  {
    id: "winf2024-9",
    title: "大規模言語モデルと人間のソーシャルネットワークにおける物語の創造的伝播 - フェイクニュースの文脈での検討 -",
    authors: [
      "椎久翔太",
      "Nori Jacoby",
      "竹内勇剛"
    ],
    venue: "第22回情報学ワークショップ",
    year: 2024,
    category: "domestic",
    topics: [
      "collective-behavior",
      "llm"
    ],
    links: {}
  },
  {
    id: "shii2023reinforcement-10",
    title: "Locating self interest in CogSci ~Ongoing Project at Max Planck Institute~",
    authors: [
      "椎久翔太"
    ],
    venue: "CogSci Meetup 2024 in Hamamatsu",
    year: 2024,
    category: "talk",
    topics: [
      "decision-making"
    ],
    links: {}
  },
  {
    id: "2-11",
    title: "小集団における創発的意見と意思決定過程の強化学習による最適化",
    authors: [
      "椎久翔太",
      "竹内勇剛"
    ],
    venue: "第38回人工知能学会全国大会",
    year: 2024,
    category: "domestic",
    topics: [
      "decision-making"
    ],
    links: {
      url: "https://confit.atlas.jp/guide/event/jsai2024/subject/4R3-OS-8b-04/date?cryptoId="
    }
  },
  {
    id: "2-12",
    title: "自己効力感の獲得による不快音の認知的マスキング",
    authors: [
      "椎久翔太",
      "竹内勇剛"
    ],
    venue: "インタラクション2024",
    year: 2024,
    category: "domestic",
    topics: [
      "music-cognition"
    ],
    links: {
      url: "https://www.interaction-ipsj.org/proceedings/2024/data/bib/1P-90.html"
    }
  },
  {
    id: "shii2023reinforcement-21",
    title: "Exploring the Mutual Adaptation of Large Language Models and Emergent Decision-Making in Simulated Small Group Interactions",
    authors: [
      "Shota Shiiku",
      "Yugo Takeuchi"
    ],
    venue: "12th International Conference on Human-Agent Interaction",
    year: 2024,
    category: "paper",
    topics: [
      "llm",
      "decision-making"
    ],
    links: {
      doi: "https://doi.org/10.1145/3687272.3688317"
    },
    selected: true
  },
  {
    id: "shii2023reinforcement-22",
    title: "Reducing Discomfort by Integrating Unpleasant Environmental Sounds with Cognitive Sound Control",
    authors: [
      "Shota Shiiku",
      "Yugo Takeuchi"
    ],
    venue: "53rd International Congress & Exposition on Noise Control Engineering",
    year: 2024,
    category: "paper",
    topics: [
      "music-cognition"
    ],
    links: {
      doi: "https://doi.org/10.3397/IN_2024_3187"
    },
    selected: true
  },
  {
    id: "shii2023reinforcement-28",
    title: "大規模言語モデルによる小集団の創発的意思決定過程の適応可能性の探究",
    authors: [
      "椎久翔太"
    ],
    venue: "認知的コミュニケーションワークショップ2024",
    year: 2024,
    category: "talk",
    topics: [
      "llm",
      "decision-making"
    ],
    links: {}
  },
  {
    id: "shii2022phd-3",
    title: "KAWAI FOUNDATION FOR SOUND TECHNOLOGY & MUSIC Research Grant",
    authors: [],
    venue: "￥500,000",
    year: 2023,
    category: "grant",
    topics: [
      "music-cognition"
    ],
    links: {}
  },
  {
    id: "2-13",
    title: "小集団で個人の意向を反映する創発的意思決定過程の強化学習による検討",
    authors: [
      "椎久翔太",
      "竹内勇剛"
    ],
    venue: "電子情報通信学会HCGシンポジウム2023",
    year: 2023,
    category: "domestic",
    topics: [
      "decision-making"
    ],
    links: {}
  },
  {
    id: "shii2023nico-14",
    title: "小集団での意思決定における個人の意向のエージェントベースモデリングによる推定",
    authors: [
      "椎久翔太",
      "竹内勇剛"
    ],
    venue: "2023年度日本認知科学会第40回大会",
    year: 2023,
    category: "domestic",
    topics: [
      "decision-making"
    ],
    links: {
      url: "https://www.jcss.gr.jp/meetings/jcss2023/proceedings/pdf/JCSS2023_P3-043.pdf"
    }
  },
  {
    id: "shii2023nico-15",
    title: "小集団での意思決定における個人の意向と行動のエージェントベースモデリングによる推定",
    authors: [
      "椎久翔太",
      "竹内勇剛"
    ],
    venue: "電子情報通信学会2023年3月HCS研究会",
    year: 2023,
    category: "domestic",
    topics: [
      "decision-making"
    ],
    links: {}
  },
  {
    id: "shii2023reinforcement-29",
    title: "小集団で個人の意向を反映する創発的意思決定過程の強化学習による検討",
    authors: [
      "椎久翔太"
    ],
    venue: "認知的コミュニケーションワークショップ2023",
    year: 2023,
    category: "talk",
    topics: [
      "decision-making",
      "llm"
    ],
    links: {}
  },
  {
    id: "shii2022phd-2",
    title: "小集団での意思決定における個人の意向と行動のエージェントベースモデリングによる推定",
    authors: [
      "椎久翔太"
    ],
    venue: "学士, 指導教員: 竹内勇剛",
    year: 2022,
    category: "thesis",
    topics: [
      "decision-making"
    ],
    links: {}
  },
  {
    id: "shii2022jiko-16",
    title: "自己効力感に着目した音環境のデザインによる不快音の認知的マスキング",
    authors: [
      "椎久翔太",
      "大本義正",
      "森田純哉",
      "高口鉄平",
      "遠山紗矢香",
      "竹内勇剛"
    ],
    venue: "第190回ヒューマンインタフェース学会研究会「コミュニケーション支援および一般（SIG-CE-25）」",
    year: 2022,
    category: "domestic",
    topics: [
      "music-cognition"
    ],
    links: {}
  },
  {
    id: "shii2022ko-30",
    title: "小集団での意思決定における個人の意向と行動のエージェントベースモデリングによる推定",
    authors: [
      "椎久翔太"
    ],
    venue: "認知的コミュニケーションワークショップ2022",
    year: 2022,
    category: "talk",
    topics: [
      "decision-making",
      "llm"
    ],
    links: {}
  },
  {
    id: "shii2020rakkyoku-17",
    title: "楽曲を利用した環境音の選択的マスキング",
    authors: [
      "椎久 翔太",
      "大本 義正",
      "森田 純哉",
      "竹内 勇剛"
    ],
    venue: "ヒューマンインタフェースサイバーコロキウム",
    year: 2020,
    category: "domestic",
    topics: [
      "music-cognition"
    ],
    links: {}
  }
];
